"""figure_provenance.py — generate PROVENANCE.md for a figures/ root.

Usage:
    python scripts/figure_provenance.py [figures_root]
    Default figures_root: parent directory of this script.
"""

# Windows' default console is cp949, which dies on Korean/symbol output.
# Force UTF-8. Use reconfigure(): wrapping in a TextIOWrapper would make it
# own the underlying stream, so once this module is imported, the caller's
# stdout gets closed when the wrapper is later garbage-collected (measured).
import sys as _sys
for _s in (_sys.stdout, _sys.stderr):
    if hasattr(_s, "reconfigure"):
        try:
            _s.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass
import sys
import os
import hashlib
import datetime
from pathlib import Path

# UTF-8 stdout guard (Korean Windows)
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

MARKER_BEGIN = "<!-- PROVENANCE_BEGIN -->"
MARKER_END = "<!-- PROVENANCE_END -->"


def sha256_prefix(path: Path, n: int = 12) -> str:
    h = hashlib.sha256()
    try:
        h.update(path.read_bytes())
        return h.hexdigest()[:n]
    except Exception:
        return "ERR"


def git_sha(path: Path) -> str:
    import subprocess
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%h", "--", str(path)],
            capture_output=True, text=True, timeout=5,
            cwd=str(path.parent)
        )
        sha = result.stdout.strip()
        return sha if sha else "untracked"
    except Exception:
        return "N/A"


def mtime_str(path: Path) -> str:
    try:
        ts = path.stat().st_mtime
        return datetime.datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M")
    except Exception:
        return "—"


def size_kb(path: Path) -> str:
    try:
        return f"{path.stat().st_size / 1024:.1f}"
    except Exception:
        return "—"


def collect_records(root: Path) -> list[dict]:
    records = []
    for folder in sorted(root.iterdir()):
        if not folder.is_dir():
            continue
        if not folder.name.startswith("F_"):
            continue

        fig_png = folder / "figure.png"
        script_py = folder / "script.py"
        data_csv = folder / "data.csv"

        record = {
            "folder": folder.name,
            "figure_mtime": mtime_str(fig_png) if fig_png.exists() else "—",
            "figure_kb": size_kb(fig_png) if fig_png.exists() else "—",
            "script_sha": git_sha(script_py) if script_py.exists() else "—",
            "script_mtime": mtime_str(script_py) if script_py.exists() else "—",
            "data_hash": sha256_prefix(data_csv) if data_csv.exists() else "—",
        }
        records.append(record)
    return records


def build_table(records: list[dict], generated_at: str) -> str:
    lines = [
        f"<!-- generated {generated_at} -->",
        "",
        "| Folder | figure.png mtime | size (KB) | script.py git SHA | script.py mtime | data.csv SHA-256[:12] |",
        "|--------|-----------------|-----------|-------------------|----------------|-----------------------|",
    ]
    for r in records:
        lines.append(
            f"| {r['folder']} | {r['figure_mtime']} | {r['figure_kb']} "
            f"| {r['script_sha']} | {r['script_mtime']} | {r['data_hash']} |"
        )
    return "\n".join(lines)


def write_provenance_md(root: Path, table: str) -> None:
    out = root / "PROVENANCE.md"
    header = "# Figure Provenance\n\nAuto-generated by `scripts/figure_provenance.py`.\n\n"
    out.write_text(header + table + "\n", encoding="utf-8")
    print(f"Written: {out}")


def update_manifest(root: Path, table: str) -> None:
    manifest = root / "MANIFEST.md"
    if not manifest.exists():
        print("MANIFEST.md not found — skipping marker update.")
        return

    content = manifest.read_text(encoding="utf-8")
    section = f"{MARKER_BEGIN}\n{table}\n{MARKER_END}"

    if MARKER_BEGIN in content and MARKER_END in content:
        before = content[: content.index(MARKER_BEGIN)]
        after = content[content.index(MARKER_END) + len(MARKER_END):]
        new_content = before + section + after
    else:
        new_content = content.rstrip() + "\n\n" + section + "\n"

    manifest.write_text(new_content, encoding="utf-8")
    print(f"Updated: {manifest}")


def main() -> None:
    if len(sys.argv) >= 2:
        root = Path(sys.argv[1])
    else:
        root = Path(__file__).parent.parent

    root = root.resolve()
    print(f"figures root: {root}")

    records = collect_records(root)
    print(f"Found {len(records)} F_* folders.")

    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    table = build_table(records, now)

    write_provenance_md(root, table)
    update_manifest(root, table)


if __name__ == "__main__":
    main()
